onlysign/src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=SessionRepository::class)
 */
class Session
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Type("\DateTimeInterface")
     */
    private $begin_date;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Type("\DateTimeInterface")
     */
    private $end_date;

    /**
     * @ORM\ManyToOne(targetEntity=Formation::class, inversedBy="sessions")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $formation;

    /**
     * @ORM\OneToMany(targetEntity=Signature::class, mappedBy="session")
     */
    private $signatures;

    /**
     * @ORM\OneToMany(targetEntity=Exception::class, mappedBy="session", cascade={"persist"})
     */
    private $exceptions;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Positive
     */
    private $code;

    public function __construct()
    {
        $this->signatures = new ArrayCollection();
        $this->exceptions = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }


    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(?Formation $formation): self
    {
        $this->formation = $formation;

        return $this;
    }

    /**
     * @return Collection|Signature[]
     */
    public function getSignatures(): Collection
    {
        return $this->signatures;
    }

    public function addSignature(Signature $signature): self
    {
        if (!$this->signatures->contains($signature)) {
            $this->signatures[] = $signature;
            $signature->setSession($this);
        }

        return $this;
    }

    public function removeSignature(Signature $signature): self
    {
        if ($this->signatures->removeElement($signature)) {
            // set the owning side to null (unless already changed)
            if ($signature->getSession() === $this) {
                $signature->setSession(null);
            }
        }

        return $this;
    }

    public function getBeginDate(): ?\DateTimeInterface
    {
        return $this->begin_date;
    }

    public function setBeginDate(\DateTimeInterface $begin_date): self
    {
        $this->begin_date = $begin_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    /**
     * @return Collection|Exception[]
     */
    public function getExceptions(): Collection
    {
        return $this->exceptions;
    }

    public function addException(Exception $exception): self
    {
        if (!$this->exceptions->contains($exception)) {
            $this->exceptions[] = $exception;
            $exception->setSession($this);
        }

        return $this;
    }

    public function removeException(Exception $exception): self
    {
        if ($this->exceptions->removeElement($exception)) {
            // set the owning side to null (unless already changed)
            if ($exception->getSession() === $this) {
                $exception->setSession(null);
            }
        }

        return $this;
    }

    public function getCode(): ?int
    {
        return $this->code;
    }

    public function setCode(?int $code): self
    {
        $this->code = $code;

        return $this;
    }
}

onlysign/src/Entity/Signature.php
<?php

namespace App\Entity;

use App\Repository\SignatureRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=SignatureRepository::class)
 */
class Signature
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean")
     * @Assert\Type("bool")
     */
    private $presence;

    /**
     * @ORM\ManyToOne(targetEntity=Session::class, inversedBy="signatures")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $session;

    /**
     * @ORM\ManyToOne(targetEntity=Profile::class, inversedBy="signatures")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $profile;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPresence(): ?bool
    {
        return $this->presence;
    }

    public function setPresence(bool $presence): self
    {
        $this->presence = $presence;

        return $this;
    }

    public function getSession(): ?Session
    {
        return $this->session;
    }

    public function setSession(?Session $session): self
    {
        $this->session = $session;

        return $this;
    }

    public function getProfile(): ?Profile
    {
        return $this->profile;
    }

    public function setProfile(?Profile $profile): self
    {
        $this->profile = $profile;

        return $this;
    }
}

onlysign/src/Form/SignatureType.php
<?php

namespace App\Form;

use App\Entity\Signature;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

class SignatureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('code', IntegerType::class)
            ->add('presence', CheckboxType::class, ["label" => "sign here", "required" => false,]);
    }
}

onlysign/src/Controller/SignatureController.php
<?php

namespace App\Controller;

use App\Entity\Signature;
use App\Form\Signature1Type;
use App\Repository\SignatureRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/signature")
 */
class SignatureController extends AbstractController
{
    /**
     * Shows you the list of all signatures
     * 
     * @Route("/", name="signature_index", methods={"GET"})
     */
    public function index(SignatureRepository $signatureRepository): Response
    {
        return $this->render('signature/index.html.twig', [
            'signatures' => $signatureRepository->findAll(),
        ]);
    }

    /**
     * Shows you the informations of the Signature you clicked on
     * 
     * @Route("/{id}", name="signature_show", methods={"GET"})
     */
    public function show(Signature $signature): Response
    {
        return $this->render('signature/show.html.twig', [
            'signature' => $signature,
        ]);
    }

    /**
     * Edit the Signature you clicked on and allows you to set the presence of someone to true or false
     * 
     * @Route("/{id}/edit", name="signature_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Signature $signature): Response
    {
        $form = $this->createForm(Signature1Type::class, $signature);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('signature_index');
        }

        return $this->render('signature/edit.html.twig', [
            'signature' => $signature,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Delete the Signature you clicked on
     * 
     * @Route("/{id}", name="signature_delete", methods={"POST"})
     */
    public function delete(Request $request, Signature $signature): Response
    {
        if ($this->isCsrfTokenValid('delete' . $signature->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($signature);
            $entityManager->flush();
        }

        return $this->redirectToRoute('signature_index');
    }
}

onlysign/templates/signature/_delete_form.html.twig
<form method="post" action="{{ path('signature_delete', {'id': signature.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ signature.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

onlysign/templates/signature/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

onlysign/templates/signature/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Signature - Onlysign{% endblock %}

{% block body %}
    <h1>Edit Signature</h1>

    {{ include('signature/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('signature_index') }}">
        <button class="btn btn-secondary">
            Back to list
        </button>
    </a>
    
    {{ include('signature/_delete_form.html.twig') }}
{% endblock %}

onlysign/templates/signature/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Signatures list - OnlySign{% endblock %}

{% block body %}
    <h1>Signatures list</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Begin date</th>
                <th>End date</th>
                <th>Last name</th>
                <th>First name</th>
                <th>Presence</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for signature in signatures %}
            <tr>
                <td>{{ signature.session.beginDate |date }}</td>
                <td>{{ signature.session.endDate |date }}</td>
                <td>{{ signature.profile.user.lastName }}</td>
                <td>{{ signature.profile.user.firstName }}</td>
                <td>{{ signature.presence ? 'Yes' : 'No' }}</td>
                <td>
                <a href="{{ path('signature_show', {'id': signature.id}) }}">
                    <button  class="btn btn-info">
                        Show
                    </button>
                </a>
                <a href="{{ path('signature_edit', {'id': signature.id}) }}">
                    <button class="btn btn-primary">
                        Edit
                    </button>
                </a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

onlysign/templates/signature/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Signature - OnlySign{% endblock %}

{% block body %}
    <h1>Signature</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ signature.id }}</td>
            </tr>
            <tr>
                <th>Presence</th>
                <td>{{ signature.presence ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('signature_index') }}">
        <button class="btn btn-secondary">
            Back to list
        </button>
    </a>

    <a href="{{ path('signature_edit', {'id': signature.id}) }}">
        <button class="btn btn-primary">
            Edit
        </button>
    </a>

    {{ include('signature/_delete_form.html.twig') }}
{% endblock %}