onlysign/src/Entity/Profile.php
<?php

namespace App\Entity;

use App\Repository\ProfileRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProfileRepository::class)
 */
class Profile
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="profiles")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Formation::class, inversedBy="profiles")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $formation;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\DateTime
     */
    private $subscription_date;

    /**
     * @ORM\OneToMany(targetEntity=Signature::class, mappedBy="profile")
     */
    private $signatures;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "The location must be at least {{ limit }} characters long",
     *      maxMessage = "The location cannot be longer than {{ limit }} characters"
     * )
     * @Assert\NotNull
     */
    private $formation_role;

    public function __construct()
    {
        $this->signatures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(?Formation $formation): self
    {
        $this->formation = $formation;

        return $this;
    }


    /**
     * @return Collection|Signature[]
     */
    public function getSignatures(): Collection
    {
        return $this->signatures;
    }

    public function addSignature(Signature $signature): self
    {
        if (!$this->signatures->contains($signature)) {
            $this->signatures[] = $signature;
            $signature->setProfile($this);
        }

        return $this;
    }

    public function removeSignature(Signature $signature): self
    {
        if ($this->signatures->removeElement($signature)) {
            // set the owning side to null (unless already changed)
            if ($signature->getProfile() === $this) {
                $signature->setProfile(null);
            }
        }

        return $this;
    }

    public function getSubscriptionDate(): ?\DateTimeInterface
    {
        return $this->subscription_date;
    }

    public function setSubscriptionDate(\DateTimeInterface $subscription_date): self
    {
        $this->subscription_date = $subscription_date;

        return $this;
    }

    public function getFormationRole(): ?string
    {
        return $this->formation_role;
    }

    public function setFormationRole(string $formation_role): self
    {
        $this->formation_role = $formation_role;

        return $this;
    }
}

onlysign/src/Form/ProfileType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Profile;
use App\Entity\Formation;
use App\Form\FormationType;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\ChoiceList\ChoiceList;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class ProfileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('subscription_date', DateType::class, [
                'widget' => 'choice',
                'data' => new \DateTime('now')
            ])
            // Create a field using a custom query rendering all formations ordered by their title
            ->add('formation', EntityType::class, [
                "class" => Formation::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('f')
                        ->orderBy('f.title', 'ASC');
                },
                'choice_label' => 'title',
            ])
            // Create a field with 3 choices of indicative roles
            ->add('role', ChoiceType::class, [
                'choices' => [
                    'Student' => 'Student',
                    'Teacher' => 'Teacher',
                    'Chief' => 'Chief',
                ]
            ])
            // Create a field using a custom query rendering all users ordered by their username
            // The "multiple" option allows you to pick many users
            ->add('user', EntityType::class, [
                "class" => User::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->orderBy('u.username', 'ASC');
                },
                'choice_label' => 'username',
                "multiple" => true,
            ]);
    }
}

onlysign/src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\Profile;
use App\Form\ProfileType;
use App\Repository\ProfileRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/profile")
 */
class ProfileController extends AbstractController
{
    /**
     * Shows you the list of all profiles. A profile is an association of 1 User and 1 Formation
     * 
     * @Route("/", name="profile_index", methods={"GET"})
     */
    public function index(ProfileRepository $profileRepository): Response
    {
        return $this->render('profile/index.html.twig', [
            'profiles' => $profileRepository->findAll(),
        ]);
    }

    /**
     * Add one or many User(s) to an existing formation, choosing his/their formation role and subscription date
     * 
     * @Route("/new", name="profile_new", methods={"GET","POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProfileType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // Get datas from the submitted form
            $data = $form->getData();

            $subscriptionDate = $data['subscription_date'];
            $formation = $data['formation'];
            $users = $data['user'];
            $role = $data['role'];

            // Add as many users you picked to the formation you choosed with a formation_role and a subscription_date
            foreach ($users as $user) {
                $profile = new Profile();
                $profile->setUser($user)
                    ->setFormation($formation)
                    ->setFormationRole($role)
                    ->setSubscriptionDate($subscriptionDate);
                $entityManager->persist($profile);
            }
            $entityManager->flush();

            return $this->redirectToRoute('profile_index');
        }

        return $this->render('profile/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * Shows you a profile (associtiation of 1 user and 1 formation)
     * 
     * @Route("/{id}", name="profile_show", methods={"GET"})
     */
    public function show(Profile $profile): Response
    {
        return $this->render('profile/show.html.twig', [
            'profile' => $profile,
        ]);
    }

    /**
     * Edit a profile (associtiation of 1 user and 1 formation)
     * 
     * @Route("/{id}/edit", name="profile_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Profile $profile): Response
    {
        $form = $this->createForm(ProfileType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('profile_index');
        }

        return $this->render('profile/edit.html.twig', [
            'profile' => $profile,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Delete a profile (associtiation of 1 user and 1 formation)
     * 
     * @Route("/{id}", name="profile_delete", methods={"POST"})
     */
    public function delete(Request $request, Profile $profile): Response
    {
        if ($this->isCsrfTokenValid('delete' . $profile->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($profile);
            $entityManager->flush();
        }

        return $this->redirectToRoute('profile_index');
    }
}

onlysign/templates/profile/_delete_form.html.twig
<form method="post" action="{{ path('profile_delete', {'id': profile.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ profile.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

onlysign/templates/profile/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}  {# <select id="meetup_sport" ... #}
    <button class="btn btn-success" formnovalidate>{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
<script>
var $sport = $('#profile');
// When sport gets selected ...
$sport.change(function() {
  // ... retrieve the corresponding form.
  var $form = $(this).closest('form');
  // Simulate form data, but only include the selected sport value.
  var data = {};
  data[$sport.attr('name')] = $sport.val();
  // Submit data via AJAX to the form's action path.
  $.ajax({
    url : $form.attr('action'),
    type: $form.attr('method'),
    data : data,
    success: function(html) {
      // Replace current position field ...
      $('#meetup_position').replaceWith(
        // ... with the returned one from the AJAX response.
        $(html).find('#meetup_position')
      );
      // Position field now displays the appropriate positions.
    }
  });
});
</script>

onlysign/templates/profile/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Profile - OnlySign{% endblock %}

{% block body %}
    <h1>Edit Profile</h1>

    {{ include('profile/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('profile_index') }}">
        <button class="btn btn-secondary">
            Back to list
        </button>
    </a>

    {{ include('profile/_delete_form.html.twig') }}
{% endblock %}

onlysign/templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profiles list - OnlySign{% endblock %}

{% block body %}
    <h1>Profiles</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Utilisateur</th>
                <th>Formation</th>
                <th>Rôle</th>
                <th>Subscription_date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for profile in profiles %}
            <tr>
                <td>{{profile.user.username}}</td>
                <td>{{profile.formation}}</td>
                    <td>{{profile.formationRole}}</td>
                <td>{{ profile.subscriptionDate|date('Y-m-d H:i:s')}}</td>
                <td>
                    <a href="{{ path('profile_show', {'id': profile.id}) }}">
                        <button class="btn btn-info">
                            Show
                        </button>
                    </a>
                    <a href="{{ path('profile_edit', {'id': profile.id}) }}">
                        <button class="btn btn-primary">
                            Edit
                        </button>
                    </a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('profile_new') }}">
        <button class="btn btn-primary">
            Create new
        </button>
    </a>
{% endblock %}

onlysign/templates/profile/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add user to formation - OnlySign{% endblock %}

{% block body %}
    <h1>Add user(s) to a formation</h1>

    {{ include('profile/_form.html.twig') }}

    <a href="{{ path('profile_index') }}">
        <button class="btn btn-secondary">
            Back to list
        </button>
    </a>
{% endblock %}

onlysign/templates/profile/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profile - OnlySign{% endblock %}

{% block body %}
    <h1>Profile</h1>

    <table class="table">
        <tbody>
             <tr>
                <th>Formation</th>
                <td>{{ profile.formation}}</td>
            </tr>
            <tr>
                <th>Utilisateur</th>
                <td>{{ profile.user}}</td>
            </tr>
            <tr>
                <th>Subscription_date</th>
                <td>{{ profile.subscriptionDate|date('Y-m-d H:i:s')}}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('profile_index') }}">
        <button class="btn btn-secondary">
            Back to list
        </button>
    </a>

    <a href="{{ path('profile_edit', {'id': profile.id}) }}">
    <button class="btn btn-primary">
    Edit
    </button>
    </a>

    {{ include('profile/_delete_form.html.twig') }}
{% endblock %}